### ISSUE TITLE
Consider using Metabase over TablePlus

### ISSUE THREAD

**Issue by eschultze** [mholt/timeliner#1]
I haven't tested your project yet, but it seems awesome. I'd like to suggest you to consider using Metabase https://www.metabase.com/ over TablePlus. The installation process is very simple and I think this project could benefit a lot from a visualization tool such as Metabase.

**Comment by mholt** [comment]
Thanks, but this actually has nothing to do with Timeliner. You are free to use whichever DB tool suits you.
