### ISSUE TITLE
Add Telegram data source

### ISSUE THREAD

**Issue by hstolte** [mholt/timeliner#17]
The Telegram desktop app has an option "Export Telegram data" as a json (or html) file including chats, contacts, media and a whole lot more...

I will try to integrate it if I find some time ;)

**Comment by hstolte** [comment]
I started working on this :)

**Comment by mholt** [comment]
Awesome! Can't wait to review it!

I responded to your email by the way. Let me know here on GitHub if you still have the problem -- just open a new issue.

**Comment by mholt** [comment]
@hstolte FYI, I've added [a new issue template](https://raw.githubusercontent.com/mholt/timeliner/master/.github/ISSUE_TEMPLATE/data_source.md) for requesting data sources which will make it easier for whoever implements it. If you could update your original post to use [this template](https://raw.githubusercontent.com/mholt/timeliner/master/.github/ISSUE_TEMPLATE/data_source.md), that would be great, thanks!

(In your case, a PR is already open - a WIP - but I'm commenting on all issues like this anyway just to be consistent.)

**Comment by mholt** [comment]
I went ahead and implemented this in [Timelinize](https://timelinize.com) (see #84 and also the README for info) but it only supports 1:1 chats, not group chats, due to some limitations in the archive format.
