### ISSUE TITLE
Add Apple data source

### ISSUE THREAD

**Issue by hstolte** [mholt/timeliner#18]
In Europe, a personal data archive can be downloaded from https://privacy.apple.com/

````
Your download will include:

    App usage and activity information as spreadsheets or files in JSON, CSV, XML or PDF format.
    Documents, photos and videos in their original format.
    Contacts, calendars and bookmarks in VCF, ICS or HTML format.

Your download will not include app, book, film, TV programme or music purchases.
````
Detailed list of apps and services:
````

    Apple Media Services information
    Apple ID account and device information
    Apple Online Store and Retail Store activity
    Apple Pay activity
    AppleCare support history, repair requests and more
    Game Center activity
    iCloud Bookmarks and Reading List
    iCloud Calendars and Reminders
    iCloud Contacts
    iCloud Drive files and documents
    iCloud Mail
    iCloud Notes
    iCloud Photos
    Maps Report an Issue
    Marketing communications, downloads and other activity
    Other data

````

**Comment by wakatara** [comment]
+ 💯

**Comment by mholt** [comment]
@hstolte FYI, I've added [a new issue template](https://raw.githubusercontent.com/mholt/timeliner/master/.github/ISSUE_TEMPLATE/data_source.md) for requesting data sources which will make it easier for whoever implements it. If you could update your original post to use [this template](https://raw.githubusercontent.com/mholt/timeliner/master/.github/ISSUE_TEMPLATE/data_source.md), that would be great, thanks!

You've already got some good information in your initial post; feel free to keep that when you fill out the template.

**Comment by mholt** [comment]
This is working or in progress in 2 forms in Timelinize (see #84 and the updated README):

- iPhone backup (plug in the iPhone, back it up)
- iCloud
