### ISSUE TITLE
Need help with installation

### ISSUE THREAD

**Issue by zblesk** [mholt/timeliner#2]
I'd like to try Timeliner out, but I'm having difficulties with installing it. I've also never used Go before. 

I've spent a lot of time trying and failing under Windows 10 and Ubuntu 18 LTS under WSL. (I haven't found any info re supported platforms. If I'd just missed it, please point me in the right direction.)

I'd installed golang successfully, then tried the `go get -u github.com/mholt/timeliner/cmd/timeliner`. 
At first it threw up errors about missing 'gcc'. I've tried installing MinGW on Windows and one of the suggested packages from apt on Ubuntu. 

After that, the Ubuntu `go get` just ran for a while, then died without printing any messages. Under Windows it threw up an error about a failing SQLite compilation and died as well. 

Are these just completely unsupported scenarios? How should I go about running Timeliner? 
(I've been writing something similar in the past month, so I'm especially eager to try it out.)

**Comment by mholt** [comment]
Ah, yeah, sorry I forgot to mention in the docs, that the SQLite dependency is unfortunately in C, not Go, so you need a C compiler.

Eventually I'll have releases with ready-to-go binaries on the Releases page, but we're not there yet. (I even finally got it to cross-compile to Linux! But not yet to Windows, I'm afraid. Shouldn't be too hard though.) Timeliner should be able to compile for any platform that Go + SQLite compiles to, which is, like, all of them. :smile:

For the long-running `go get`, use `go get -v` to see verbose output. That will tell you where it's hanging.

But other than having a C compiler and your Go env set up correctly (you can use `go env` to ensure that the `CGO_*`flags are all set properly, as well as `CC=` should be your C compiler -- in my experience these are all correct by default), it should "just work".

**Comment by zblesk** [comment]
Ah, thanks. 
I've tried that under WSL, with the `-v` flag. When it finished... I've found a `timeliner.exe` executable. 
I admit to having no clue how I ended up building under Ubuntu and getting a windows .exe file, but... eh. 😅  

Anyway, when I ran it under Windows in Powershell, it seems to be working. Thank you for your quick response.

**Comment by Kryptonit3** [comment]
damn... is this for Windows? No wonder I couldn't get it working on ubuntu.
