### ISSUE TITLE
error replacing data file database locked

### ISSUE THREAD

**Issue by blob42** [mholt/timeliner#21]
Thanks for this great tool. 

Any idea what must be provoking this error:
```Processing item graph: processing node of item graph: replacing data file with identical existing file: querying DB: database is locked```

**Comment by mholt** [comment]
I've seen this before... is the database being accessed by any other processes?

**Comment by blob42** [comment]
I was running two instances with two different accounts, it might have been related. Closing this issue.

**Comment by mholt** [comment]
Ah yup, that'd do it.
