### ISSUE TITLE
add support for postgress sql

### ISSUE THREAD

**Issue by prabirshrestha** [mholt/timeliner#28]

**Comment by mholt** [comment]
Can you please give a detailed description of what you mean? Enough so that someone who is going to work on the issue can sit down, know what you want done, and actually implement it.

**Comment by prabirshrestha** [comment]
Currently it data is stored in sqlite db. I would like to run this in the cloud so would be good if I could use other db such as postgresql.

**Comment by mholt** [comment]
(Closing for same reason as described in #30)
