### ISSUE TITLE
Document database structure

### ISSUE THREAD

**Issue by konradrej** [mholt/timeliner#33]
Documenting how the database is structured could be useful for starting work on an interface. I'm looking at it and without some digging it's hard to understand what some of the stuff is. For example the "class" for "items" is, I assume based on this however it's not clear

https://github.com/mholt/timeliner/blob/3284be867396f6f5d8e2c850d165b099f06541bd/itemgraph.go#L134-L144

**Comment by mholt** [comment]
Yeah, this is a good point, sorry I never got around to it.

The DB schema is here: https://github.com/mholt/timeliner/blob/3284be867396f6f5d8e2c850d165b099f06541bd/db.go#L49

As for the item classes, `iota` is just a keyword meaning auto-incrementing integer, so `ClassUnknown = 0`, `ClassImage = 1`, etc.

**Comment by konradrej** [comment]
Thanks for the explanation, don't worry too much about it. You probably had a lot of different things to think about related to this project.
