### ISSUE TITLE
Interface design/type

### ISSUE THREAD

**Issue by konradrej** [mholt/timeliner#37]
# Type
Should it have a web interface or a desktop one? Maybe both? Possibly add an API to make it easier to create different types of interfaces. Should it be available from other devices? For example through the web or a phone app. Should import be available through the interface and if you have "external" interfaces (phone, web etc) should you be able to import it from there?

I think an API and a local only interface for import. Import (and other modification) shouldn't be available on other devices unless password protection is added.

# Design (for a graphical interface)
A timeline sounds like a good idea (based of name). Should you be able to sort it by type (video, audio, image, place etc)? Separate more detailed views for each month while only providing a overview on the timeline?

I think a timeline with general month views and then a more detailed monthly view would be good, since it's supposed to be a long term collection then a general yearly view might be good too.

Any more suggestions?

**Comment by mholt** [comment]
Oh, this reminds me I need to share my UI mockup. Will get around to that soon.

**Comment by mholt** [comment]
See #84
