### ISSUE TITLE
Authenticating via CLI

### ISSUE THREAD

**Issue by sorbe88** [mholt/timeliner#45]
I'm trying to use this directly on my NAS (a Synology DS218j), so I'm runnig it via Linux command line with no browser access.

I have timeliner installed and ready to run, but I can't authenticate as I can't open a browser within command line.

Is there a way to get around that and authenticate via the command line?

**Comment by mholt** [comment]
Authenticate on your desktop, then move it to your NAS.

(The readme suggests this:)

> ... This is your timeline. You can move it around if you want ...
