### ISSUE TITLE
go get results in a "cannot find package" error on Windows 10

### ISSUE THREAD

**Issue by trosel** [mholt/timeliner#49]
![image](https://user-images.githubusercontent.com/1299322/69561049-bbd5d000-0f7a-11ea-961a-9cd5fbab0fd2.png)

On windows 10 if you do the install command `$ go get -u github.com/mholt/timeliner/cmd/timeliner
` you get the above error.

Not sure how to resolve it. I have the latest go version by the way.

**Comment by joonas-fi** [comment]
(edit: scroll below for solution)

Same here, but am running Ubuntu Linux (on a Docker container), `go1.13.1 linux/amd64`

**Comment by joonas-fi** [comment]
Not sure if these issues were 1:1 related (I am building outside of GOPATH), but PR https://github.com/mholt/timeliner/pull/48 fixes this

Concrete steps to get a build from that PR going:

```
$ git clone https://github.com/fawick/timeliner.git
$ cd timeliner/cmd/timeliner/
$ go build
```

Bob's your uncle. :+1: for the PR!

**Comment by joonas-fi** [comment]
@mholt, if the PR merge takes some time, could we temporarily add a link to this issue under the "Install" section in README so new users don't get discouraged by installation being too hard? If you want, I can send the README PR I suggested.

**Comment by mholt** [comment]
Merged, thanks for the bump!
