### ISSUE TITLE
Stuck on authorization screen

### ISSUE THREAD

**Issue by JVTEAM** [mholt/timeliner#55]
I put in the command to setup google photos. It pulls up the browser to login.  I get all the way to where I'm confirming my choices to allow my app access.  Then it just churns with a "waiting for localhost" in the bottom left.  Am I just not patient enough?  Does this take a long time?

**Comment by mholt** [comment]
Is there any output in the terminal?

**Comment by JVTEAM** [comment]
Embarrassingly all that was needed was to close the browser.
