### ISSUE TITLE
Instagram import error: "extra text: +00:00"

### ISSUE THREAD

**Issue by jacroe** [mholt/timeliner#59]
I'm receiving errors almost immediately after trying to import an Instagram export. Error:

```
2020/06/28 03:13:07 [ERROR][instagram/jacroe] Importing: importing: parsing photo time 2020-02-15T04:08:11+00:00 into format 2006-01-02T15:04:05: parsing time "2020-02-15T04:08:11+00:00": extra text: +00:00
```

The `media.json` file has data that looks like

```json
{
  "photos": [
    {
      "caption": "A superb caption",
      "taken_at": "2020-02-15T04:08:11+00:00",
      "location": "Sanford, Florida",
      "path": "photos/202002/12345678901234567890abcdefabcdef.jpg"
    }
  ]
}
```

while the `takenAtFormat` within [`instagram.go`](https://github.com/mholt/timeliner/blob/master/datasources/instagram/instagram.go#L137) is set to `2006-01-02T15:04:05`.

Looks like Instagram is now providing explicit timezone information.

**Comment by jacroe** [comment]
Every single `taken_at` value in my `media.json` file had `+00:00` tacked on at the end. Stripping that had Timeliner importing the export fine.

**Comment by mholt** [comment]
Ah, indeed, it looks like Instagram changed their time format. Should be easy enough to fix!
