### ISSUE TITLE
Is my usage case covered here?

### ISSUE THREAD

**Issue by Bitwolfies** [mholt/timeliner#61]
Simply all I want to do is export all my google photos data (google takeout consistently missed photos)and have what would be stored in a json, imbedded as exif data, and keeping my albums in tact.

**Comment by Bitwolfies** [comment]
With the ability to import the photos after where I please of course.

**Comment by mholt** [comment]
I think so, more or less. Takeout should have everything though; the Google Photos API strips location data, unfortunately. :(
