### ISSUE TITLE
Go get install results in lz4 package error

### ISSUE THREAD

**Issue by ianmaddox** [mholt/timeliner#65]
When running the command
`go get github.com/mholt/timeliner/cmd/timeliner`
you get the following error:
```
 % go get github.com/mholt/timeliner/cmd/timeliner
package github.com/pierrec/lz4/v4: cannot find package "github.com/pierrec/lz4/v4" in any of:
        /usr/local/go/src/github.com/pierrec/lz4/v4 (from $GOROOT)
        /home/ian/go/src/github.com/pierrec/lz4/v4 (from $GOPATH)
```
Per their documentation , the new lz4 install command is as follows:
`go get github.com/pierrec/lz4`

**Comment by mholt** [comment]
Discussed and resolved in https://github.com/mholt/timeliner/issues/54
