### ISSUE TITLE
can't install with install command

### ISSUE THREAD

**Issue by alex116** [mholt/timeliner#66]
System: ubuntu 20.04
Kernel: 5.4.0-52-generic  x86-64
go version go1.13.8
```
go get github.com/mholt/timeliner/cmd/timeliner
package github.com/pierrec/lz4/v4: cannot find package "github.com/pierrec/lz4/v4" in any of:
    /usr/lib/go-1.13/src/github.com/pierrec/lz4/v4 (from $GOROOT)
    /home/alex/go/src/github.com/pierrec/lz4/v4 (from $GOPATH)
```

**Comment by alex116** [comment]
https://github.com/pierrec/lz4/issues/77

**Comment by sirnacnud** [comment]
It doesn't seem like this is fixed, I also ran in to this with go1.15.5 on macoS 10.14.6

```
$ go get github.com/mholt/timeliner/cmd/timeliner
cannot find package "github.com/mholt/timeliner/datasources/gmail" in any of:
	/usr/local/Cellar/go/1.15.5/libexec/src/github.com/mholt/timeliner/datasources/gmail (from $GOROOT)
	/Users/duncan/go/src/github.com/mholt/timeliner/datasources/gmail (from $GOPATH)
cannot find package "github.com/pierrec/lz4/v4" in any of:
	/usr/local/Cellar/go/1.15.5/libexec/src/github.com/pierrec/lz4/v4 (from $GOROOT)
	/Users/duncan/go/src/github.com/pierrec/lz4/v4 (from $GOPATH)
```

**Comment by lmcdasm** [comment]
seems not to be fixes as well in the chain from pierrec/lz4 to mholt/archiver as well
[dasm@dev-machine1 art-cli]$ go build main.go
../github.com/mholt/archiver/lz4.go:8:2: cannot find package "github.com/pierrec/lz4/v4" in any of:
        /usr/local/go/src/github.com/pierrec/lz4/v4 (from $GOROOT)
        /home/dasm/go/src/github.com/pierrec/lz4/v4 (from $GOPATH)
