### ISSUE TITLE
Similarity to another repo: Perkeep

### ISSUE THREAD

**Issue by gabefair** [mholt/timeliner#81]
[Brad Fitzpatrick](https://github.com/bradfitz)  (of OpenID, Go, and Tailscale fame) created a project called [Perkeep](https://perkeep.org/). Described on their [github](https://github.com/perkeep/perkeep)  as: "your personal storage system for life: a way of storing, syncing, sharing, modelling and backing up content."
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/2096785/159885423-9903cfa2-96e2-4b9e-9744-f1bf4749599d.png">
- Pros
  - Written in *GO*
  - RESTful backend
  - Documented Well
  - Code is written and organized with modularity in mind
- Cons
  - Could use a better FrontEnd
  - Progress has been slower since Brad left Google: https://github.com/perkeep/perkeep/commits

From my point of view Perkeep could be an amazing backend for this timeliner (Life OS) personal data warehouse project.

**Comment by gabefair** [comment]
See the [readme](https://github.com/mholt/timeliner)

**Comment by mholt** [comment]
Yeah, as you saw in the README, Perkeep is a very different project:

> Yeah, I know this is very similar to what [Perkeep](https://perkeep.org/) does. Perkeep is a way cooler project in my opinion. However, Perkeep is more about storage and sync, whereas Timeliner is more focused on constructing relationships between items and projecting your digital life onto a single timeline. If Perkeep is my unified personal data storage, then Timeliner is my automatic journal. (Believe me, my heart sank after I realized that I was almost rewriting parts of Perkeep, until I decided that the two are different enough to warrant a separate project.)

Thank you for your sponsorship btw!

**Comment by infogulch** [comment]
As you note these projects aren't quite in the same lane, but have you considered using Perkeep as a/the backend store for timeliner data? These projects are very closely aligned in values and approach but they operate in a different layer so they seem quite complimentary from what I can see. It seems like they could both benefit from a tighter collaboration. E.g. eventually timeliner will need to solve sync and storage as data grows; and perkeep really needs a better ui. (An "automatic journal" like timeliner's ought to be the default view of all of these kinds of projects.)

**Comment by mholt** [comment]
I don't think layering the complexity of Perkeep underneath Timeliner is really going to be helpful. Timeliner just stores things to the file system and indexes them with a sqlite db, and this has scaled to millions of items so far. I think if physical storage is a limitation then that can certainly be solved by implementing solutions at the storage layer (like raid, etc.) but I don't think it needs to integrate with Timeliner.

**Comment by infogulch** [comment]
I think that's a reasonable perspective, thanks for responding!
