### ISSUE TITLE
Google Photos Data Source not registered

### ISSUE THREAD

**Issue by hugosanchezmartinez** [mholt/timeliner#83]
Hi, 
First, thanks for this script, will be very helpful :) 
I followed all the stuff to connect to google-photos data source. However, I'm getting a FATAL.
Creating data source client: data source not registered: google-photos

Not sure if need to "publish the app" for this or not. Not sure either if this is the problem. 
The browser opened to get the consent of my account and everything was smooth until:
timeliner get-all google-photos/MY_MAIL@gmail.com

Any help on this? Thanks in advance,
H

**Comment by mholt** [comment]
It's actually `google_photos` not `google-photos` :wink: 

PS. Could I interest you in trying Timeliner's successor, Timelinize? https://twitter.com/timelinize -- it's in private alpha/dev previews currently.

**Comment by hugosanchezmartinez** [comment]
Oh boy, can't believe this typo from my side. :P kill me!
Thanks!
Yup, happy to try Timelinize! 
Cheers!
H

**Comment by mholt** [comment]
@hugosanchezmartinez Join our Discord and you can access the download and documentation for Timelinize: https://discord.gg/gRXYVeaX

**Comment by hugosanchezmartinez** [comment]
THanks! Going to Discord now :) cheers!
